require 'yaml'

if (File.exists?(".vagrant/hosts.yaml"))
    current_dir     = File.dirname(File.expand_path(__FILE__))
    cfg             = YAML.load_file(".vagrant/hosts.yaml")

    network_type    = cfg["network"]["type"]
    environment     = cfg["environment"]
    hosts           = cfg["hosts"]
else
    puts "ERROR: Hosts file .vagrant/hosts.yaml does not exist!"
    exit 1
end

puts "Creating VMs for environment: " + environment + " ..."
puts "Configuring network_type: " + network_type + " ..."

Vagrant.configure("2") do |config|
    config.ssh.insert_key = false
    config.ssh.forward_agent = true
    config.vm.synced_folder ".", "/vagrant", id: "vagrant-root", disabled: true

    hosts.each do |name, ip|
        config.vm.define name do |machine|
            if network_type == "public"
                machine.vm.network :public_network
            else
                machine.vm.network :private_network
            end

            machine.vm.hostname = name
            machine.vm.box = "ubuntu-22.04.1-x86_64.vmf"

            machine.vm.provider "vmware_fusion" do |v|
                v.gui = true
                v.ssh_info_public = true
                v.linked_clone = true
                v.vmx['displayname'] = name
                v.vmx["ethernet0.pcislotnumber"] = "32"
                v.vmx["ethernet1.pcislotnumber"] = "35"
            end

            machine.vm.provision "dummy", type: "shell" do |s|
                s.inline = "Hello Moto"
                s.privileged = false
            end
        end

#         config.vm.define name do |machine|
#             machine.vm.box = "ubuntu-22.04.1-x86_64.vbox"
#             machine.vm.network :private_network, ip: ip
#             machine.vm.hostname = name
#
#             machine.vm.provider "virtualbox" do |vb|
#                 vb.name = name
#                 vb.linked_clone = true
#             end
#
#             machine.vm.provision "dummy", type: "shell" do |s|
#                 s.inline = "Hello Moto"
#                 s.privileged = false
#              end
#         end
    end
end


