- name: Make tmp folder
  ansible.builtin.file:
    path: tf/tmp
    state: directory
    mode: '0755'

- name: Substitute tfvars
  template:
    src: templates/tfvars.j2
    dest: "{{ playbook_dir }}/tf/tmp/env.tfvars"

- name: Create hosts file
  ansible.builtin.shell:
    cmd: 'cat {{ playbook_dir }}/inventory/inventory.yaml | grep ansible_host  | sed "s/^[ \t]*ansible\_host: /- /g" > {{ playbook_dir }}/tf/tmp/hosts'

- name: 'Display output: Create hosts file'
  debug:
    msg: "{{ lookup('file','{{ playbook_dir }}/tf/tmp/hosts') }}"

- name: Init Terraform
  shell: |
    cd {{ playbook_dir }}/tf;
    terraform init
  when: (operation == "init")
  register: init

- name: 'Display output: Init Terraform'
  debug:
    msg: "{{ init.stdout }}"
  when: (operation == "init")

- name: Create resources - Plan
  shell: |
    cd {{ playbook_dir }}/tf;
    terraform workspace new {{ env }}
    terraform workspace select {{ env }}
    terraform plan -var-file=tmp/env.tfvars -out=tmp/plan.tfplan;
  when: (operation == "create-plan")
  register: create_plan

- name: 'Display output: Create resources - Plan'
  debug:
    msg: "{{ create_plan.stdout }}"
  when: (operation == "create-plan")

- name: Create resources
  shell: |
    cd {{ playbook_dir }}/tf;
    terraform workspace select {{ env }}
    terraform apply tmp/plan.tfplan
  when: (operation == "create")
  register: create

- name: 'Display output: Create resources'
  debug:
    msg: "{{ create.stdout }}"
  when: (operation == "create")

- name: Destroy resources
  shell: |
    cd {{ playbook_dir }}/tf;
    terraform workspace new {{ env }}
    terraform workspace select {{ env }}
    terraform destroy -var-file=tmp/env.tfvars -auto-approve
  when: (operation == "destroy")
  register: destroy

- name: 'Display output: Destroy resources'
  debug:
    msg: "{{ destroy.stdout }}"
  when: (operation == "destroy")