- name: K3s Worker nodes
  hosts: k3s_worker_nodes
  roles:
    - k3s

  vars:
    node_token: "{{ lookup('file','/tmp/node-token') }}"
    control_node_url: "{{ lookup('file','/tmp/control-node-url') }}"
