Vagrant.configure("2") do |config|
    config.vm.box = "ubuntu/jammy64"

    config.ssh.insert_key = false
    config.ssh.forward_agent = true
    check_guest_additions = false
    functional_vboxsf = false

    config.vm.provider "virtualbox" do |vb|
        vb.name = "k3s-cluster-base-box"
        vb.memory = 4096
        vb.cpus = 2
    end

end