require 'yaml'

current_dir  = File.dirname(File.expand_path(__FILE__))
hosts        = YAML.load_file("#{current_dir}/tmp/hosts")

Vagrant.configure("2") do |config|
    puts "Hosts: #{hosts}"

    config.vm.box = "k3s-cluster-base"

    config.ssh.insert_key = false
    config.ssh.forward_agent = true
    check_guest_additions = false
    functional_vboxsf = false

    hosts.each_with_index do |ip, index|
        name = "node#{index + 1}"

        addr = ip.split('.')
        ssh_host = "#{addr[0]}.#{addr[1]}.*.*"

        puts "SSH_HOST: #{ssh_host}"
        puts "Machine Name: #{name}"

        config.vm.define name do |machine|
            machine.vm.network :private_network, ip: ip
            machine.vm.hostname = name

            machine.vm.provider "virtualbox" do |vb|
                vb.name = name
                vb.linked_clone = true
            end

            machine.vm.provision "file", source: "~/.ssh/id_rsa.pub", destination: "/home/vagrant/id_rsa.pub"
            machine.vm.provision "ssh_keys", type: "shell" do |s|
                s.env = { 'SSH_HOST' => ssh_host }

                s.path = "scripts/bootstrap.sh"
                s.privileged = false
              end
         end
    end
end