- name: Make vagrant tmp folder
  ansible.builtin.file:
    path: "{{ playbook_dir }}/vagrant/.vagrant"
    state: directory
    mode: '0755'

- fail: msg="Operation is not defined"
  when: (operation is undefined or operation|length == 0)

- fail: msg="Environment is not defined"
  when: (env is undefined or env|length == 0)

- fail: msg="VM count is not defined"
  when: (operation == "init" and (vm_count is undefined or vm_count|length == 0))

- name: Vagrant Init
  shell: |
    cd {{ playbook_dir }}/vagrant

    if [ -e ".vagrant/hosts" ]; then rm .vagrant/hosts; fi
    
    for INDEX in {1..{{ vm_count }}}
    do
      echo "- node$INDEX-{{ env }}" >> .vagrant/hosts
    done
  when: (operation == "init")
      
- name: 'Make role/vars folder'
  ansible.builtin.file:
    path: "{{ role_path }}/vars"
    state: directory
    mode: '0755'
  when: (operation == "inventory-vars")

- name: Make inventory folder
  ansible.builtin.file:
    path: "{{ playbook_dir }}/inventory"
    state: directory
    mode: '0755'
  when: (operation == "inventory")

- name: Create inventory vars
  shell: |
    cd {{ playbook_dir }}/vagrant;
    vagrant ssh-config | grep -E -i -w 'Host|Hostname' >> tmp
    echo "#auto generated by vagrant role" > {{ role_path }}/vars/main.yaml
    echo "hosts:" >> {{ role_path }}/vars/main.yaml
    sed -r 's/Host (.*)([0-9]+)(.*)/\ \ \host\2:\n\ \ \ \ host: \1\2\3/' tmp | sed -r 's/.*HostName (.*)/\ \ \ \ ip: \1/' >> {{ role_path }}/vars/main.yaml
    rm tmp
  when: (operation == "inventory-vars")

- name: Create Ansible inventory
  template:
    src: templates/k3s-cluster-inventory.j2
    dest: "{{ playbook_dir }}/inventory/k3s-cluster-inventory.yaml"
    trim_blocks: true
  when: (operation == "inventory")
