- name: Bootstrap host
  import_tasks: bootstrap.yaml
  when: (operation == "bootstrap")

- name: K3s Server tasks
  import_tasks: k3s-server.yaml
  when: (operation == "k3s-server")

- name: K3s Agent tasks
  import_tasks: k3s-agent.yaml
  when: (operation == "k3s-agent")

- name: K3s Istio tasks
  import_tasks: k3s-istio.yaml
  when: (operation == "k3s-istio")

